/**
 * The attribute block of a character.
 * @typedef AttributeBlock
 * @type {object}
 * @property {number} brawn Brawn (BN).
 * @property {number} daring Daring (DG).
 * @property {number} tenacity Tenacity (TY).
 * @property {number} heart Heart (HT).
 * @property {number} sagacity Sagacity (SY).
 * @property {number} cunning Cunning (CG).
 */ 

/**
 * A wound received by a character.
 * @typedef Wound
 * @type {object}
 * @property {string} type Type of the wound ('cleaving', 'blunt', 'piercing', 'other').
 * @property {number} level Severity of the wound, from 1 to 7.
 * @property {number} bl Blood Loss (BL) rating of the wound.
 * @property {number} shock Shock generated by the wound.
 * @property {number} pain Pain generated by the wound. This value is the raw Pain level.
 * @property {number} [kd] KnockDown check QoS required to avoid falling prone.
 * @property {number} [ko] KnockOut check QoS required to avoid falling unconscious.
 */

/** @type {Map.<string, Wound} */
const woundsMap = new Map();

function setupFakeWounds() {
    /** @type {Wound} */
    let wound;

    // Hand (left), Minor (3), Cleaving
    wound = {
        type: "cleaving",
        level: 3,
        bl: 2,
        shock: 6,
        pain: 6
    };
    woundsMap.set("11l", wound);

    // Shin (right), Slight (2), Blunt
    wound = {
        type: "blunt",
        level: 2,
        bl: 0,
        shock: 4,
        pain: 4,
        kd: 1
    };
    woundsMap.set("14r", wound);
}

setupFakeWounds();